### DISCUSSION TITLE
[Request] Flatpak version of StreamFX for OBS

### DISCUSSION THREAD

**Discussion by Sethox** [Xaymar/obs-stream-effects#840] [Ideas & Feedback]
### Explain the Feature/Enhancement

I believe it would make some Linux users from any distribution easier if there exists a Flatpak version of this plugin. Easier up-to-date package maintainer from this project. 

### What makes this feature/enhancement useful for StreamFX and its users?

Flatpak being _Linux distribution_ agnostic (on any Linux box that has Flatpak installed) can use this. 

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [ ] There is no other way to currently do this in StreamFX or OBS Studio.

### Any additional Information we need to know?

[Here is a link for more information about how to create a plugin for OBS in Flatpak](https://github.com/flathub/com.obsproject.Studio/wiki/Plugins#distributing-plugins-on-flathub).

**Comment by Xaymar** [comment]
[Method 2](https://github.com/flathub/com.obsproject.Studio/wiki/Plugins#method-2-config-folder) is already supported, you just need to extract it to a different location as shown on the guide you linked.

**Comment by pmartiner** [comment]
@Xaymar thank you for clarifying. The main reason I support the request is that, at least with method 2, OBS is not able to stream with AMF encoding (I don't know if this also with NVENC as well), but the option does appear on the regular OBS bin. If there's a workaround for this issue, maybe it's not necessary to port the plugin

**Comment by Xaymar** [comment]
Unfortunately, I have no reason to support Flatpak since StreamFX already works just fine on the target platforms. There is no return on the investment of time into this for me, the only entity benefitting from this is the Flatpak project. As such, I have no reason to support it myself, but I'll leave this open in case anyone else wants to add Flatpak packaging to StreamFX _and maintain it forever_.

**Comment by rmnvgr** [comment]
Hello,

I started writing a Flatpak for StreamFX, and got it working. This is the manifest:

<details>

<summary><code>org.obsproject.Studio.Plugin.StreamFX.yml</code></summary>

```yaml
id: com.obsproject.Studio.Plugin.StreamFX
branch: stable
runtime: com.obsproject.Studio
runtime-version: stable
sdk: org.kde.Sdk//5.15-21.08
build-extension: true
separate-locales: false
appstream-compose: false
build-options:
  prefix: /app/plugins/StreamFX

modules:
  - name: streamfx
    buildsystem: cmake-ninja
    config-opts:
      - -DSTRUCTURE_PACKAGEMANAGER=true
      - -DENABLE_UPDATER=false
      - -DENABLE_FRONTEND=true
      - -DREQUIRE_JSON=true
    build-options:
      cxxflags: '-isystem /app/include/obs'
    post-install:
      - install -Dm644 --target-directory=${FLATPAK_DEST}/share/metainfo ${FLATPAK_ID}.metainfo.xml
      - appstream-compose --basename=${FLATPAK_ID} --prefix=${FLATPAK_DEST} --origin=flatpak ${FLATPAK_ID}
    sources:
      - type: git
        url: https://github.com/Xaymar/obs-StreamFX.git
        tag: 0.11.1
        commit: 81a9699846609385b64a177ed6a2826d77ad97cd
      - type: file
        path: com.obsproject.Studio.Plugin.StreamFX.metainfo.xml
      # Don't download headers and libraries and fix library name
      - type: patch
        path: streamfx.patch

```

</details>

I faced three issues in the process:

- When setting `ENABLE_UPDATER` to `false` (required since the updates will be handled directly by Flatpak), the build fails because it still needs `nlohmann/json.hpp` in `source/ui/ui-about.cpp` but its directory is not added to the include directories. I fixed it by manually setting `REQUIRE_JSON` to `true`, but it'd be better to always require it.
- On Flathub you can't download files during the build process, and since we already have all the headers and libraries from OBS, I commented the downloads in `CMakeLists.txt` and forced the presence of the front-end. I'm not familiar with CMake, but it'd be nice to not download additional files if the dependencies are present on the system.
- The library name, with this setup, is `obs` and not `libobs`.

This is the patch I applied to make it build:

<details>

<summary><code>streamfx.patch</code></summary>

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index acaa87c..65be527 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -444,15 +444,15 @@ if(NOT ${PREFIX}OBS_NATIVE)
 	endif()
 
 	# Download libOBS
-	download_project(
-		PROJ libobs
-		URL "${_DOWNLOAD_OBS_URL}"
-		URL_HASH "${_DOWNLOAD_OBS_HASH}"
-		DOWNLOAD_NO_PROGRESS OFF
-		UPDATE_DISCONNECTED OFF
-	)
+	#download_project(
+	#	PROJ libobs
+	#	URL "${_DOWNLOAD_OBS_URL}"
+	#	URL_HASH "${_DOWNLOAD_OBS_HASH}"
+	#	DOWNLOAD_NO_PROGRESS OFF
+	#	UPDATE_DISCONNECTED OFF
+	#)
 
-	include("${libobs_SOURCE_DIR}/cmake/LibObs/LibObsConfig.cmake")
+	#include("${libobs_SOURCE_DIR}/cmake/LibObs/LibObsConfig.cmake")
 endif()
 
 ################################################################################
@@ -981,7 +981,7 @@ if(REQUIRE_NVIDIA_CUDA AND D_PLATFORM_WINDOWS)
 endif()
 
 #- OBS Front-End API
-set(HAVE_OBSFE OFF)
+set(HAVE_OBSFE ON)
 if(REQUIRE_OBSFE)
 	if(${PREFIX}OBS_NATIVE)
 		if(TARGET obs-frontend-api)
@@ -1079,7 +1079,7 @@ if(D_PLATFORM_WINDOWS) # Windows Support
 endif()
 
 # Minimum Dependencies
-list(APPEND PROJECT_LIBRARIES libobs)
+list(APPEND PROJECT_LIBRARIES obs)
 
 # Components
 if(HAVE_CURL)
```

</details>

Furthermore, Flathub requires [AppStream metadata](https://www.freedesktop.org/software/appstream/docs/). I wrote this one:

<details>

<summary><code>com.obsproject.Studio.Plugin.StreamFX.metainfo.xml</code></summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<component type="addon">
	<id>com.obsproject.Studio.Plugin.StreamFX</id>
	<extends>com.obsproject.Studio</extends>
	<name>StreamFX</name>
	<summary>Additional sources, filters, transitions and encoders for OBS Studio</summary>
	<description>
	<p>StreamFX is a plugin to libOBS (OBS Studio, StreamElements OBS Live) that adds new sources, filters and transitions to give you the ability to drastically improve your stream and recording setup past what was possible in OBS Studio until now. Whether it is blurring out a region, moving something in 3D, or just writing your own shaders as a new transition, source or filter - StreamFX has it all.</p>
	</description>
	<url type="homepage">https://streamfx.xaymar.com/</url>
	<url type="bugtracker">https://github.com/Xaymar/obs-StreamFX/issues</url>
	<url type="contact">https://s.xaymar.com/streamfx-dc</url>
	<url type="donation">https://github.com/Xaymar/obs-StreamFX/wiki#support-streamfx-on-github-sponsors-or-patreon</url>
	<url type="translate">https://crowdin.com/project/obs-stream-effects</url>
	<metadata_license>CC0-1.0</metadata_license>
	<project_license>GPL-2.0</project_license>
</component>
```

</details>

AppStream is not specific to Flatpak though, and are used by front-end package installers, so you may want to upstream it so other packagers can make use of it.

If you're fine with this, I can submit it to Flathub, and I'll be maintaining it.
